fixed options in mpdev_cleanup, mpdev_update

diff --git a/create_rpm b/create_rpm
--- a/create_rpm
+++ b/create_rpm
@@ -1,12 +1,41 @@
 #!/bin/sh
 # $Log: create_rpm,v $
+# Revision 1.2  2020-07-16 12:39:08+05:30  Cprogrammer
+# fixed release numbering
+#
 # Revision 1.1  2020-07-08 11:38:06+05:30  Cprogrammer
 # Initial revision
 #
 #
-# $Id: create_rpm,v 1.1 2020-07-08 11:38:06+05:30 Cprogrammer Exp mbhangui $
+# $Id: create_rpm,v 1.2 2020-07-16 12:39:08+05:30 Cprogrammer Exp mbhangui $
 #
 version=$(cat conf-version)
+
+verbose=0
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    --verbose)
+	verbose=1
+    ;;
+    --release=*)
+	release=$optarg
+    ;;
+    *)
+    echo "invalid option [$1]"
+    read key
+    usage 1
+    ;;
+    esac
+
+    shift
+done
 
 if test -f $HOME/.rpmmacros
 then
@@ -63,9 +92,7 @@ if [ $copy_src -eq 1 ] ; then
 fi
 
 dist=`uname -r |cut -d . -f4`
-if [ $# -gt 0 ] ; then
-	release=$1
-else
+if [ -z "$release" ] ; then
 	if [ -f /usr/bin/mpdev ] ; then
 		mdist=$(rpm -qf /usr/bin/mpdev|cut -d- -f3|cut -d. -f3)
 		if [ " $dist" = " $mdist" ] ; then
@@ -87,34 +114,42 @@ fi
 echo -n "Build RPM for mpdev-"$version"-1."$release" (Y/N) - "
 read key
 if [ " $key" = " Y" -o " $key" = " y" ] ; then
-	cp mpdev/mpdev.spec /tmp
-	sed -i -e "s|^Release: .*|Release: 1.$release%{?dist}|g" /tmp/mpdev.spec
-	if [ $? -eq 0 ] ; then
-		tmprel=`cat mpdev/conf-release 2>/dev/null`
-		if [ ! " $tmprel" = " 1.$release" ] ; then
-			echo 1.$release > mpdev/conf-release
-			make -s mpdev/mpdev.spec
-			cp mpdev/mpdev.spec /tmp
-			cd mpdev/debian
-			make -s
-			cd ../..
-		fi
+	tmprel=`cat mpdev/conf-release 2>/dev/null`
+	if [ ! " $tmprel" = " 1.$release" ] ; then
+		cd mpdev
+		echo 1.$release > conf-release
+		make -s mpdev.spec
+		cp mpdev.spec /tmp
+		make -C debian -s
+		cd ../..
+	else
+		cp mpdev/mpdev.spec /tmp
 	fi
-	rpmbuild -ba --clean /tmp/mpdev.spec
-	/bin/rm /tmp/mpdev.spec
 	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
-	rpm --addsign $rpmbuild/RPMS/$build_arch/mpdev-"$version"-"1.$release".$dist.$build_arch.rpm
-	echo -n "RPM lint for mpdev-"$version"-1."$release" (Y/N) - "
-	read key
-	if [ " $key" = " Y" -o " $key" = " y" ] ; then
-		(
-		echo mpdev
-		rpmlint $rpmbuild/RPMS/$build_arch/mpdev-"$version"-"1.$release".$dist.$build_arch.rpm
-		echo ------------------------
-		echo mpdev-"$version"-"1.$release".$dist.src.rpm
-		rpmlint $rpmbuild/SRPMS/mpdev-"$version"-"1.$release".$dist.src.rpm
-		echo ------------------------
-		) 2>&1 | less
+	if [ $verbose -eq 0 ] ; then
+		echo "rpmbuild -ba --clean --quiet /tmp/mpdev.spec"
+		rpmbuild -ba --clean --quiet /tmp/mpdev.spec
+	else
+		echo "rpmbuild -ba --clean --quiet /tmp/mpdev.spec"
+		rpmbuild -ba --clean /tmp/mpdev.spec
+	fi
+	if [ $? -eq 0 ] ; then
+		/bin/rm /tmp/mpdev.spec
+		rpm --addsign $rpmbuild/RPMS/$build_arch/mpdev-"$version"-"1.$release".$dist.$build_arch.rpm
+		echo -n "RPM lint for mpdev-"$version"-1."$release" (Y/N) - "
+		read key
+		if [ " $key" = " Y" -o " $key" = " y" ] ; then
+			(
+			echo mpdev
+			rpmlint $rpmbuild/RPMS/$build_arch/mpdev-"$version"-"1.$release".$dist.$build_arch.rpm
+			echo ------------------------
+			echo mpdev-"$version"-"1.$release".$dist.src.rpm
+			rpmlint $rpmbuild/SRPMS/mpdev-"$version"-"1.$release".$dist.src.rpm
+			echo ------------------------
+			) 2>&1 | less
+		fi
+	else
+		/bin/rm /tmp/mpdev.spec
 	fi
 else
 	/bin/rm -rf /tmp/mpdev-"$version"
