added -r option to show earliest played song first

diff --git a/mpdhist.in b/mpdhist.in
--- a/mpdhist.in
+++ b/mpdhist.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: mpdhist.in,v 1.2 2022-09-26 20:18:34+05:30 Cprogrammer Exp mbhangui $
+# $Id: mpdhist.in,v 1.3 2022-09-26 21:12:59+05:30 Cprogrammer Exp mbhangui $
 #
 
 usage()
@@ -13,6 +13,11 @@ Known values for OPTION are:
 -l limit
 --limit=limit
   Finds song with uri matching path
+
+-r
+--reverse
+  Reverse the order with song heard first
+  at the top
 
 -h
 --help
@@ -29,36 +34,41 @@ get_mpd_conf_value()
 
 process_cmdline()
 {
-OPTS=$(getopt -o l:h --long limit:,help -- "$@")
+OPTS=$(getopt -o l:hr --long limit:,help,reverse -- "$@")
 if [ $? -ne 0 ] ; then
-	usage 1
+  usage 1
 fi
 #echo "OPTS=$OPTS"
 #echo "args=$@"
 eval set -- "$OPTS"
 while true; do
-	case "$1" in
-	-l|--limit)
-		limit=$2
-		shift 2
-	;;
-	-h|--help)
-		usage 0
-	;;
-	--)
-		shift
-		break
-	;;
-	*)
-		echo "invalid option [$1]" 1>&2
-		usage 1;
-		break
-	;;
-	esac
+  case "$1" in
+  -l|--limit)
+    limit=$2
+    shift 2
+  ;;
+  -r|--reverse)
+    do_rev=1
+	shift
+  ;;
+  -h|--help)
+    usage 0
+  ;;
+  --)
+    shift
+    break
+  ;;
+  *)
+    echo "invalid option [$1]" 1>&2
+    usage 1;
+    break
+  ;;
+  esac
 done
 }
 
 limit=24
+do_rev=0
 process_cmdline "$@"
 
 music_dir=`get_mpd_conf_value music_directory`
@@ -80,15 +90,25 @@ fi
 stmt=""
 stmt="$stmt select id, title, artist, album, play_count, rating, "
 stmt="$stmt strftime('%d-%m-%Y %H:%M:%S', datetime(last_played, 'unixepoch', 'localtime'))  "
-stmt="$stmt from song order by last_played DESC LIMIT $limit"
+if [ $do_rev -eq 0 ] ; then
+  stmt="$stmt from song where last_played is NOT NULL and play_count > 0 order by last_played DESC LIMIT $limit"
+else
+  stmt="$stmt from song where last_played is NOT NULL and play_count > 0 order by last_played ASC LIMIT $limit"
+fi
+
+echo "sqlite3 -header -batch -column $stats_file $stmt"
+
 sqlite3 -header -batch -column $stats_file "$stmt" | \
-	sed \
-		-e 's/[ \t]\+$//' \
-		-e 's{strftime.*${Last Played{' \
-		-e 's{ -*${ ==================={'
+  sed \
+    -e 's/[ \t]\+$//' \
+    -e 's{strftime.*${Last Played{' \
+    -e 's{ -*${ ==================={'
 
 #
 # $Log: mpdhist.in,v $
+# Revision 1.3  2022-09-26 21:12:59+05:30  Cprogrammer
+# added -r option to show earliest played song first
+#
 # Revision 1.2  2022-09-26 20:18:34+05:30  Cprogrammer
 # pass -header option to sqlite3
 #
