player.in: return db operation 5 times on failure

diff --git a/player.in b/player.in
--- a/player.in
+++ b/player.in
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 #
-# $Id: player.in,v 1.54 2024-12-23 19:08:35+05:30 Cprogrammer Exp mbhangui $
+# $Id: player.in,v 1.55 2025-02-11 23:11:43+05:30 Cprogrammer Exp mbhangui $
 #
 get_mpd_conf_value()
 {
@@ -62,11 +62,23 @@ sticker_db_insert()
 	fi
 	turi=`echo $1|sed -e "s{'{''{g"`
 	tmprate=$2
-	sqlite3 -batch $sticker_file "INSERT or IGNORE into sticker \
-		(type, uri, name, value) values ('song', '$turi', 'rating', $tmprate);"
-	if [ $? -ne 0 ] ; then
+	for i in 1 2 3 4 5
+	do
+		sqlite3 -batch $sticker_file "INSERT or IGNORE into sticker \
+			(type, uri, name, value) values ('song', '$turi', 'rating', $tmprate);"
+		if [ $? -eq 0 ] ; then
+			ret=0
+			break
+		fi
+		ret=1
+		sleep 0.5
+	done
+	if [ $ret -ne 0 ] ; then
 		echo "ERROR: INSERT or IGNORE into sticker (type, uri, name, value) into sticker values ('song', '$turi', 'rating', $tmprate);" 1>&2
 		return 1
+	fi
+	if [ $VERBOSE -eq 1 ] ; then
+		echo "[$i]: Success stats db insert"
 	fi
 	return 0
 }
@@ -80,11 +92,24 @@ sticker_db_update()
 	fi
 	turi=`echo $1|sed -e "s{'{''{g"`
 	tmprate=$2
-	sqlite3 -batch $sticker_file "UPDATE sticker SET value=$tmprate WHERE type='song' AND uri='$turi';"
-	if [ $? -ne 0 ] ; then
+	for i in 1 2 3 4 5
+	do
+		sqlite3 -batch $sticker_file "UPDATE sticker SET value=$tmprate WHERE type='song' AND uri='$turi';"
+		if [ $? -eq 0 ] ; then
+			ret=0
+			break
+		fi
+		ret=1
+		sleep 0.5
+	done
+	if [ $ret-ne 0 ] ; then
 		echo "ERROR: UPDATE sticker SET value=$tmprate WHERE type='song' AND uri='$turi';" 1>&2
 		return 1
 	fi
+	if [ $VERBOSE -eq 1 ] ; then
+		echo "[$i]: Success stats db update"
+	fi
+	return 0
 }
 
 stats_db_insert()
@@ -108,10 +133,19 @@ stats_db_insert()
 	ALBUM=`echo "$SONG_ALBUM" | sed -e "s{'{''{g"`
 	TITLE=`echo "$SONG_TITLE" | sed -e "s{'{''{g"`
 	tmprate=$2
-	sqlite3 -batch $stats_file "INSERT or IGNORE into \
-		song (uri, play_count, last_played, rating, duration,last_modified,artist,album,title,track,genre,date) \
-		values ('$turi',0,0,$tmprate,$SONG_DURATION,$SONG_LAST_MODIFIED,'$ARTIST','$ALBUM','$TITLE','$SONG_TRACK','$SONG_GENRE','$SONG_DATE');"
-	if [ $? -ne 0 ] ; then
+	for i in 1 2 3 4 5
+	do
+		sqlite3 -batch $stats_file "INSERT or IGNORE into \
+			song (uri, play_count, last_played, rating, duration,last_modified,artist,album,title,track,genre,date) \
+			values ('$turi',0,0,$tmprate,$SONG_DURATION,$SONG_LAST_MODIFIED,'$ARTIST','$ALBUM','$TITLE','$SONG_TRACK','$SONG_GENRE','$SONG_DATE');"
+		if [ $? -eq 0 ] ; then
+			ret=0
+			break
+		fi
+		ret=1
+		sleep 0.5
+	done
+	if [ $ret -ne 0 ] ; then
 		(
 		echo -n "INSERT or IGNORE into song "
 		echo -n "(uri, play_count, last_played, rating, duration,"
@@ -122,6 +156,9 @@ stats_db_insert()
 		echo
 		) 1>&2
 		return 1
+	fi
+	if [ $VERBOSE -eq 1 ] ; then
+		echo "[$i]: Success stats db insert"
 	fi
 	return 0
 }
@@ -158,17 +195,44 @@ stats_db_update()
 			if [ $VERBOSE -gt 0 ] ; then
 				echo "UPDATE stats upgrade KARMA += $kval"
 			fi
-			sqlite3 -batch $stats_file \
-				"UPDATE song SET last_played=$last_played, play_count=play_count+1, rating=$tmprate, karma=karma+$kval WHERE uri='$turi';"
+			for i in 1 2 3 4 5
+			do
+				sqlite3 -batch $stats_file \
+					"UPDATE song SET last_played=$last_played, play_count=play_count+1, rating=$tmprate, karma=karma+$kval WHERE uri='$turi';"
+				if [ $? -eq 0 ] ; then
+					ret=0
+					break
+				fi
+				ret=1
+				sleep 0.5
+			done
 		else
-			sqlite3 -batch $stats_file \
-				"UPDATE song SET last_played=$last_played, play_count=play_count+1, rating=$tmprate WHERE uri='$turi';"
+			for i in 1 2 3 4 5
+			do
+				sqlite3 -batch $stats_file \
+					"UPDATE song SET last_played=$last_played, play_count=play_count+1, rating=$tmprate WHERE uri='$turi';"
+				if [ $? -eq 0 ] ; then
+					ret=0
+					break
+				fi
+				ret=1
+				sleep 0.5
+			done
 		fi
 	else
-		sqlite3 -batch $stats_file \
-			"UPDATE song SET last_played=$last_played, rating=$tmprate WHERE uri='$turi';"
+		for i in 1 2 3 4 5
+		do
+			sqlite3 -batch $stats_file \
+				"UPDATE song SET last_played=$last_played, rating=$tmprate WHERE uri='$turi';"
+			if [ $? -eq 0 ] ; then
+				ret=0
+				break
+			fi
+			ret=1
+			sleep 0.5
+		done
 	fi
-	if [ $? -ne 0 ] ; then
+	if [ $ret -ne 0 ] ; then
 		if [ $update_playcount -eq 1 ] ; then
 			if [ $kval -gt 0 ] ; then
 				echo "ERROR: UPDATE song SET last_played=$last_played, play_count=play_count+1, rating=$tmprate, karma=karma+$kval WHERE uri='$turi';"
@@ -179,6 +243,9 @@ stats_db_update()
 			echo "ERROR: UPDATE song SET last_played=$last_played, rating=$tmprate WHERE uri='$turi';" 1>&2
 		fi
 		return 1
+	fi
+	if [ $VERBOSE -eq 1 ] ; then
+		echo "[$i]: Success stats db update"
 	fi
 	return 0
 }
@@ -191,11 +258,23 @@ downgrade_karma()
 		fi
 	fi
 	turi=`echo "$1" | sed -e "s{'{''{g"`
-	sqlite3 -batch $stats_file \
-		"UPDATE song SET karma=karma-1 WHERE uri='$turi' AND karma>0 AND karma<60 AND rating<6 AND play_count<=5;"
-	if [ $? -ne 0 ] ; then
+	for i in 1 2 3 4 5
+	do
+		sqlite3 -batch $stats_file \
+			"UPDATE song SET karma=karma-1 WHERE uri='$turi' AND karma>0 AND karma<60 AND rating<6 AND play_count<=5;"
+		if [ $? -eq 0 ] ; then
+			ret=0
+			break
+		fi
+		ret=1
+		sleep 0.5
+	done
+	if [ $ret -ne 0 ] ; then
 		"ERROR: UPDATE song SET karma=karma-1 WHERE uri='$turi' AND karma>0 AND karma<60 AND rating<6 AND play_count<=5;" 1>&2
 		return 1
+	fi
+	if [ $VERBOSE -eq 1 ] ; then
+		echo "[$i]: Success downgrade karma"
 	fi
 	return 0
 }
@@ -218,6 +297,9 @@ scrobble()
 				--album="$S_ALBUM" --track="$S_TITLE" \
 				--duration="$SONG_DURATION"
 		fi
+		if [ $VERBOSE -eq 1 ] ; then
+			echo "END lastfm scrobble"
+		fi
 	fi
 	if [ -n "$SCROBBLE_LIBREFM" ] ; then
 		if [ $VERBOSE -eq 1 ] ; then
@@ -231,6 +313,9 @@ scrobble()
 			librefm-scrobbler --update --artist="$S_ARTIST" \
 				--album="$S_ALBUM" --track="$S_TITLE" \
 				--duration="$SONG_DURATION"
+		fi
+		if [ $VERBOSE -eq 1 ] ; then
+			echo "END librefm scrobble"
 		fi
 	fi
 }
@@ -303,9 +388,11 @@ update_song()
 	else
 		# you can have ratings maintained in sticker or stats or both
 		if [ $sticker_enabled -eq 1 ] ; then
-			rating=`get_mpd_rating "$uri"`
+			sticker_rating=`get_mpd_rating "$uri"`
+			rating=$sticker_rating
 		elif [ $stats_enabled -eq 1 ] ; then
-			rating=`get_stats_rating "$uri"`
+			stats_rating=`get_stats_rating "$uri"`
+			rating=$stats_rating
 		else
 			echo "Nothing to do"
 			exit 0
@@ -319,15 +406,20 @@ update_song()
 				rating=0
 			fi
 			inserted=1
-			if [ $sticker_enabled -eq 1 ] ; then
-				if [ ! -f $MPDEV_TMPDIR/sticker.$csum ] ; then
+			if [ -z "$sticker_rating" -o $sticker_rating -eq 0 ] ; then
+				if [ $sticker_enabled -eq 1 ] ; then
 					sticker_db_insert "$uri" "$rating"
-					touch $MPDEV_TMPDIR/sticker.$csum
+					if [ ! -f $MPDEV_TMPDIR/sticker.$csum ] ; then
+						touch $MPDEV_TMPDIR/sticker.$csum
+					fi
 				fi
-			elif [ $stats_enabled -eq 1 ] ; then
-				if [ ! -f $MPDEV_TMPDIR/stats.$csum ] ; then
+			fi
+			if [ -z "$stats_rating" -o $stats_rating -eq 0 ] ; then
+				if [ $stats_enabled -eq 1 ] ; then
 					stats_db_insert "$uri" "$rating"
-					touch $MPDEV_TMPDIR/stats.$csum
+					if [ ! -f $MPDEV_TMPDIR/stats.$csum ] ; then
+						touch $MPDEV_TMPDIR/stats.$csum
+					fi
 				fi
 			fi
 		elif [ $rating -eq 0 ] ; then
@@ -340,16 +432,20 @@ update_song()
 			fi
 			if [ $rating -gt 0 ] ; then
 				inserted=2
-				if [ $sticker_enabled -eq 1 ] ; then
-					if [ ! -f $MPDEV_TMPDIR/sticker.$csum ] ; then
+				if [ -z "$sticker_rating" -o $sticker_rating -eq 0 ] ; then
+					if [ $sticker_enabled -eq 1 ] ; then
 						sticker_db_update "$uri" "$rating"
-						touch $MPDEV_TMPDIR/sticker.$csum
+						if [ ! -f $MPDEV_TMPDIR/sticker.$csum ] ; then
+							touch $MPDEV_TMPDIR/sticker.$csum
+						fi
 					fi
-				elif  [ $stats_enabled -eq 1 ] ; then
-					if [ ! -f $MPDEV_TMPDIR/stats.$csum ] ; then
-						# update rating
+				fi
+				if [ -z "$stats_rating" -o $stats_rating -eq 0 ] ; then
+					if  [ $stats_enabled -eq 1 ] ; then
 						stats_db_update "$uri" "$rating" "$START_TIME" 0
-						touch $MPDEV_TMPDIR/stats.$csum
+						if [ ! -f $MPDEV_TMPDIR/stats.$csum ] ; then
+							touch $MPDEV_TMPDIR/stats.$csum
+						fi
 					fi
 				fi
 			fi
@@ -418,9 +514,12 @@ update_song()
 			START_TIME=`cat $MPDEV_TMPDIR/start_time.$csum`
 		fi
 		if [ $stats_enabled -eq 1 -a ! -f $MPDEV_TMPDIR/stats.$csum ] ; then
-			stats_db_insert "$uri" "$rating"
-			if [ $VERBOSE -gt 0 -a $no_db_update -eq 0 ] ; then
-				echo "INSERT stats rating=$rating  Start=$START_TIME"
+			stats_rating=`get_stats_rating "$uri"`
+			if [ -z "$stats_rating" -o $stats_rating -eq 0 ] ; then
+				if [ $VERBOSE -gt 0 -a $no_db_update -eq 0 ] ; then
+					echo "INSERT stats rating=$rating  Start=$START_TIME"
+				fi
+				stats_db_insert "$uri" "$rating"
 			fi
 			touch $MPDEV_TMPDIR/stats.$csum
 		fi
@@ -464,10 +563,11 @@ update_song()
 		if [ $stats_enabled -eq 1 ] ; then
 			# update rating + playcount
 			if [ -f $MPDEV_TMPDIR/stats_playcount.$csum ] ; then
-				stats_db_update "$uri" "$rating" "$START_TIME" 0
+				sticker_rating=`get_mpd_rating "$uri"`
 				if [ $VERBOSE -gt 0 -a $no_db_update -eq 0 ] ; then
-					echo "UPDATE stats Start=$START_TIME End=$END_TIME rating=[$rating]"
+					echo "UPDATE stats Start=$START_TIME End=$END_TIME org_rating=[$rating], rating=[$sticker_rating]"
 				fi
+				stats_db_update "$uri" "$sticker_rating" "$START_TIME" 0
 			else
 				if [ -n "$SONG_PLAYED_DURATION" ] ; then
 					if [ $var -eq 0 ] ; then
@@ -488,14 +588,15 @@ update_song()
 					if [ -n "$pcount_s" ] ; then
 						pcount_s=$(expr $pcount_s + 1)
 					fi
+					sticker_rating=`get_mpd_rating "$uri"`
 					if [ $VERBOSE -gt 0 -a $no_db_update -eq 0 ] ; then
 						if [ -z "$pcount_s" ] ; then
-							echo "UPDATE stats Playcount rating=[$rating] Start=$START_TIME End=$END_TIME"
+							echo "UPDATE stats Playcount Playcount=1, org_rating=[$rating], rating=[$sticker_rating] Start=$START_TIME End=$END_TIME"
 						else
-							echo "UPDATE stats Playcount Playcount=$pcount_s, rating=[$rating] Start=$START_TIME End=$END_TIME"
+							echo "UPDATE stats Playcount Playcount=$pcount_s, org_rating=[$rating], rating=[$sticker_rating] Start=$START_TIME End=$END_TIME"
 						fi
 					fi
-					stats_db_update "$uri" "$rating" "$START_TIME" 1
+					stats_db_update "$uri" "$sticker_rating" "$START_TIME" 1
 					touch $MPDEV_TMPDIR/stats_playcount.$csum
 				else
 					pcount_s=""
@@ -598,6 +699,9 @@ fi
 exit 0
 
 # $Log: player.in,v $
+# Revision 1.55  2025-02-11 23:11:43+05:30  Cprogrammer
+# return db operation 5 times on failure
+#
 # Revision 1.54  2024-12-23 19:08:35+05:30  Cprogrammer
 # do now downgrade karma on pause-song
 #
