added upgrade karma logic

diff --git a/player.in b/player.in
--- a/player.in
+++ b/player.in
@@ -1,6 +1,9 @@
 #!/bin/sh
 #
 # $Log: player.in,v $
+# Revision 1.22  2021-04-16 21:11:02+05:30  Cprogrammer
+# added upgrade karma logic
+#
 # Revision 1.21  2021-04-15 20:06:06+05:30  Cprogrammer
 # skip db update if NO_DB_UPDATE is defined and non-zero
 #
@@ -68,7 +71,7 @@
 # Initial revision
 #
 #
-# $Id: player.in,v 1.21 2021-04-15 20:06:06+05:30 Cprogrammer Exp mbhangui $
+# $Id: player.in,v 1.22 2021-04-16 21:11:02+05:30 Cprogrammer Exp mbhangui $
 #
 get_mpd_conf_value()
 {
@@ -145,6 +148,17 @@ get_stat_rating()
 	sqlite3 -batch $stats_file "SELECT rating from song where uri='$turi';"
 	if [ $? -ne 0 ] ; then
 		echo "error: SELECT rating from song where uri='$turi';" 1>&2
+		return 1
+	fi
+	return 0
+}
+
+get_stat_last_played()
+{
+	turi=`echo $1|sed -e "s{'{''{g"`
+	sqlite3 -batch $stats_file "SELECT last_played from song where uri='$turi';"
+	if [ $? -ne 0 ] ; then
+		echo "error: SELECT last_played from song where uri='$turi';" 1>&2
 		return 1
 	fi
 	return 0
@@ -234,17 +248,45 @@ stats_db_update()
 	last_played=$3
 	update_playcount=$4
 	if [ $update_playcount -eq 1 ] ; then
-		sqlite3 -batch $stats_file \
-			"UPDATE song set last_played=$last_played, play_count=play_count+1, rating=$tmprate where uri='$turi';"
+		if [ -n "$prev_last_played" ] ; then
+			days_back=$(expr \( $last_played - $prev_last_played \) / 86400)
+			if [ $days_back -lt 1 ] ; then
+				kval=4
+			elif [ $days_back -lt 7 ] ; then
+				kval=3
+			elif [ $days_back -lt 14 ] ; then
+				kval=2
+			elif [ $days_back -lt 28 ] ; then
+				kval=1
+			else
+				kval=0
+			fi
+		else
+			kval=0
+		fi
+		if [ $kval -gt 0 ] ; then
+			if [ $VERBOSE -gt 0 ] ; then
+				echo "UPDATE stats upgrade KARMA += $kval"
+			fi
+			sqlite3 -batch $stats_file \
+				"UPDATE song set last_played=$last_played, play_count=play_count+1, rating=$tmprate, karma=karma+$kval where uri='$turi';"
+		else
+			sqlite3 -batch $stats_file \
+				"UPDATE song set last_played=$last_played, play_count=play_count+1, rating=$tmprate where uri='$turi';"
+		fi
 	else
 		sqlite3 -batch $stats_file \
 			"UPDATE song set last_played=$last_played, rating=$tmprate where uri='$turi';"
 	fi
 	if [ $? -ne 0 ] ; then
 		if [ $update_playcount -eq 1 ] ; then
-			echo  "ERROR: UPDATE song set last_played=$last_played, play_count=play_count+1, rating=$tmprate where uri='$turi';" 1>&2
+			if [ $kval -gt 0 ] ; then
+				echo "ERROR: UPDATE song set last_played=$last_played, play_count=play_count+1, rating=$tmprate, karma=karma+$kval where uri='$turi';"
+			else
+				echo "ERROR: UPDATE song set last_played=$last_played, play_count=play_count+1, rating=$tmprate where uri='$turi';" 1>&2
+			fi
 		else
-			echo  "ERROR: UPDATE song set last_played=$last_played, rating=$tmprate where uri='$turi';" 1>&2
+			echo "ERROR: UPDATE song set last_played=$last_played, rating=$tmprate where uri='$turi';" 1>&2
 		fi
 		return 1
 	fi
@@ -571,7 +613,7 @@ update_song()
 			if [ -f $HOME/.mpdev/AUTO_RATING ] ; then
 				rating=`cat $HOME/.mpdev/AUTO_RATING`
 			elif [ -n "$AUTO_RATING" ] ; then
-				rating=$AUTO_RATING # assign average rating of 3 for unrated music
+				rating=$AUTO_RATING # assign default rating as per value of AUTO_RATING
 			else
 				rating=0
 			fi
@@ -599,10 +641,15 @@ update_song()
 			inserted=0
 		fi
 	fi
+	prev_last_played=$(get_stat_last_played "$1")
 	if [ $VERBOSE -gt 0 ] ; then
 		if [ ! -f $MPDEV_TMPDIR/rating.$csum -a " $state" = " now-playing" ] ; then
 			echo -n "NewSong [$csum] Start=$START_TIME [`date +"%Y-%m-%d %H:%M:%S" --date=@"$START_TIME"`] "
 			echo    "duration=$SONG_DURATION rating=[$rating]"
+			if [ -n "$prev_last_played" ] ; then
+				days_back=$(expr \( $START_TIME - $prev_last_played \) / 86400)
+				echo    "  LAST PLAYED=$days_back days back [`date +"%Y-%m-%d %H:%M:%S" --date=@"$prev_last_played"`]"
+			fi
 			echo    "uri=[$uri]"
 			if [ $inserted -eq 1 ] ; then
 				if [ $sticker_enabled -eq 1 ] ; then
@@ -636,18 +683,18 @@ update_song()
 			START_TIME=`cat $MPDEV_TMPDIR/start_time.$csum`
 		fi
 		if [ $stats_enabled -eq 1 -a ! -f $MPDEV_TMPDIR/stats.$csum ] ; then
+			stats_db_insert "$uri" "$rating"
 			if [ $VERBOSE -gt 0 ] ; then
 				echo "INSERT stats rating=$rating  Start=$START_TIME"
 			fi
-			stats_db_insert "$uri" "$rating"
 			touch $MPDEV_TMPDIR/stats.$csum
 		fi
 		if [ $sticker_enabled -eq 1 -a -n "$ROMPR" -a ! -f $MPDEV_TMPDIR/rompr.$csum ] ; then
+			rompr_rating_update "$uri" "$START_TIME" "$rating"
 			if [ $VERBOSE -gt 0 ] ; then
 				tmp1=`expr "$rating" / 2`
 				echo "UPDATE RompR rating=$tmp1  Start=$START_TIME"
 			fi
-			rompr_rating_update "$uri" "$START_TIME" "$rating"
 			touch $MPDEV_TMPDIR/rompr.$csum
 		fi
 		if [ -n "$SCROBBLE_LIBREFM" -o -n "$SCROBBLE_LASTFM" ] ; then
@@ -698,24 +745,24 @@ update_song()
 					# rompr Rating table has a newer entry
 					tmp=`expr $rompr_rating \* 2`
 					if [ $tmp -ne $rating ] ; then
-						if [ $VERBOSE -gt 0 ] ; then
-							echo "UPDATE stker from RompR new=$tmp old=$rating, TTindex=$TTindex, Times=old[$START_TIME], new[$tstamp]"
-						fi
 						rating=$tmp
 						# update sticker with rating from rompr
 						sticker_db_update "$uri" $rating
+						if [ $VERBOSE -gt 0 ] ; then
+							echo "UPDATE stker from RompR new=$tmp old=$rating, TTindex=$TTindex, Times=old[$START_TIME], new[$tstamp]"
+						fi
 						echo $rating > $MPDEV_TMPDIR/rating.$csum
 					fi
 				elif [ $old_rating -gt 0 ] && [ $old_rating -ne $rating ] ; then # sticker table has a newer entry
 					# sticker table has a newer entry
 					echo $rating > $MPDEV_TMPDIR/rating.$csum
+					# update rompr with rating from sticker
+					rompr_rating_update "$uri" "$START_TIME" "$rating" "$TTindex"
 					if [ $VERBOSE -gt 0 ] ; then
 						tmp1=`expr "$rating" / 2`
 						tmp2=`expr "$old_rating" / 2`
 						echo "UPDATE RompR from stker new=$tmp1 old=$tmp2, TTindex=$TTindex, Times=old[$START_TIME], new[$START_TIME]"
 					fi
-					# update rompr with rating from sticker
-					rompr_rating_update "$uri" "$START_TIME" "$rating" "$TTindex"
 				fi
 			fi
 		fi
@@ -723,15 +770,15 @@ update_song()
 		if [ $stats_enabled -eq 1 ] ; then
 			# update rating + playcount
 			if [ -f $MPDEV_TMPDIR/stats_playcount.$csum ] ; then
+				stats_db_update "$uri" "$rating" "$START_TIME" 0
 				if [ $VERBOSE -gt 0 ] ; then
 					echo "UPDATE stats Start=$START_TIME End=$END_TIME rating=[$rating]"
 				fi
-				stats_db_update "$uri" "$rating" "$START_TIME" 0
 			else
+				stats_db_update "$uri" "$rating" "$START_TIME" 1
 				if [ $VERBOSE -gt 0 ] ; then
 					echo "UPDATE stats Playcount Start=$START_TIME End=$END_TIME rating=[$rating]"
 				fi
-				stats_db_update "$uri" "$rating" "$START_TIME" 1
 				touch $MPDEV_TMPDIR/stats_playcount.$csum
 			fi
 		fi
@@ -739,6 +786,7 @@ update_song()
 		if [ -n "$ROMPR" ] ; then
 			if [ -n "$TTindex" ] ; then
 				if [ ! -f $MPDEV_TMPDIR/rompr_playcount.$csum ] ; then
+					rompr_update_playcount "$rompr_uri" "$START_TIME" "$TTindex"
 					if [ $VERBOSE -gt 0 ] ; then
 						line=`get_rompr_playcount_ts "$TTindex"`
 						if [ -z "$line" ] ; then
@@ -756,7 +804,6 @@ update_song()
 							echo "[`date +"%Y-%m-%d %H:%M:%S" --date=@"$END_TIME"`] updated by mpdev"
 						fi
 					fi
-					rompr_update_playcount "$rompr_uri" "$START_TIME" "$TTindex"
 					touch $MPDEV_TMPDIR/rompr_playcount.$csum
 				fi
 			fi
