skip service creation if daemontools is not installed

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -41,12 +41,16 @@ esac
 # generated by other debhelper scripts.
 
 #DEBHELPER#
+if [ ! -x ${prefix}/sbin/minisvc ] ; then
+	echo "${prefix}/sbin/minisvc not found: Proceeding without creating mpdev service" 1>&2
+	exit 0
+fi
 if [ $upgrade -eq 1 ] ; then # upgrade
 	# refresh mpdev services
 	if [ ! -f /service/mpdev/variables/.options ] ; then
-	mkdir -p /service/mpdev/variables
-	echo "/usr/libexec/mpdev/create_service --servicedir=/service --user=1000 --add-service" \
-		> /service/mpdev/variables/.options
+		mkdir -p /service/mpdev/variables
+		echo "/usr/libexec/mpdev/create_service --servicedir=/service --user=1000 --add-service" \
+			> /service/mpdev/variables/.options
 	fi
 	${prefix}/sbin/minisvc --servicedir=/service --refreshsvc="/service/mpdev" --silent
 	# start mpdev services after upgrade
diff --git a/mpdev.spec.in b/mpdev.spec.in
--- a/mpdev.spec.in
+++ b/mpdev.spec.in
@@ -161,6 +161,10 @@ fi
 if [ -z "$argv1" ] ; then
   argv1=0
 fi
+if [ ! -x %{_prefix}/sbin/minisvc ] ; then
+  echo "%{_prefix}/sbin/minisvc not found: Proceeding without creating mpdev service" 1>&2
+  exit 0
+fi
 # we are doing upgrade
 if [ $argv1 -eq 2 ] ; then # upgrade
   if [ -d /run ] ; then
